src/Parakeet.Net.Web/Controllers/ProjectController.cs
using Common.Dtos;
using Common.Entities;
using Common.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Parakeet.Net.Attributes;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using Common.Enums;
using Microsoft.AspNetCore.Http;

namespace Parakeet.Net.Controllers
{
    /// <summary>
    /// 项目
    /// </summary>
    //[ApiExplorerSettings(GroupName = "V3")]
    //[CustomRoute(VersionType.V2)]
    [Route("/api/parakeet/project/[action]")]
    public class ProjectController : BaseNetEntityController<Project>
    {
        private readonly IWebHostEnvironment _environment;
        private readonly IProjectAppService _projectAppService;
        public ProjectController(IProjectAppService projectAppService, IWebHostEnvironment environment) : base(projectAppService)
        {
            _projectAppService = projectAppService;
            _environment = environment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ProjectMap(InputIdDto input)
        {
            ViewBag.ProjectId = input.Id;
            return View();
        }

        [HttpGet]
        public IActionResult Map()
        {
            var filePath = Path.Combine(_environment.WebRootPath, $@"/upload/projectMap/default.jpg");
            //var fs = new FileStream(filePath, FileMode.Open, FileAccess.Read);
            //文件名必须编码，否则会有特殊字符(如中文)无法在此下载。
            string encodeFilename = HttpUtility.UrlEncode(Path.GetFileName(filePath), Encoding.GetEncoding("UTF-8"));
            Response.Headers.Append("Content-Disposition", "inline; filename=" + encodeFilename);
            return File(filePath, "image/png");
        }

        /// <summary>
        /// UploadFile Request.Form.Files接收文件 Request.Form["uploadGuid"]传递uploadGuid
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> UploadFile(InputIdDto input)//IFormFile uploadFile参数文件过大使用参数获取会出现序列化错误
        {
            await _projectAppService.UploadFile(input);
            return SJson();
        }

        /// <summary>
        /// 下载题库文件
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public virtual async Task<IActionResult> Tiku()
        {
            var filePath = Path.Combine(_environment.WebRootPath, $@"/upload/files/题库专家_1.0.6.apk");
            //var fs = new FileStream(filePath, FileMode.Open, FileAccess.Read);
            //return File(fs, "application/vnd.android.package-archive");
            //文件名必须编码，否则会有特殊字符(如中文)无法在此下载。
            string encodeFilename = HttpUtility.UrlEncode(Path.GetFileName(filePath), Encoding.GetEncoding("UTF-8"));
            Response.Headers.Append("Content-Disposition", "attachment; filename=" + encodeFilename);
            return File(filePath, "application/vnd.android.package-archive");
        }


        [HttpGet]
        [CustomRoute(VersionType.V1)]
        public IActionResult Error()
        {
            var path = $@"{_environment.WebRootPath}/upload/projectMap/default.jpg";
            //Stream fs = new FileStream(filePath, FileMode.Open,FileAccess.Read);
            Response.Headers.Append("content-disposition", "inline; filename=default.jpg");
            return File(path, "image/jpg");
        }

        [HttpGet]
        [CustomRoute(VersionType.V2, "Error")]
        public IActionResult Error2()
        {
            var path = $@"{_environment.WebRootPath}/upload/projectMap/default.jpg";
            //Stream fs = new FileStream(filePath, FileMode.Open,FileAccess.Read);
            Response.Headers.Append("content-disposition", "inline; filename=default.jpg");
            return File(path, "image/jpg");
        }
    }
}

src/Parakeet.Net.Web/Views/Project/ProjectMap.cshtml
<div class="project-map-container row">

    <div class="col-md-10 col-md-offset-1">
        <div class="gallery-scorll">
            <div id="project-map-gallery"></div>
            @*<img id="project-map" title="项目导图" src="@Url.Action("Map")" onerror="onerror=null;width='300';src='@Url.Action("Error")'" width="100%" />*@
        </div>
    </div>

    <div class="col-md-10 col-md-offset-1">
        <div id="project-map-upload"></div>
    </div>
    <div class="col-md-10 col-md-offset-1">
        <span>允许图片扩展名: <span> .png .jpg .gif .bmp</span>.</span>
        <span>文件大小限制: <span>6 MB.</span></span>
    </div>
</div>

<div id="contextMenu"></div>


<script>
    $(function() {
        //更换ProjectMap图片
        var config = dxConfig.fileUploader({
            name: 'uploadFile',
            uploadUrl: '@Url.Action("UploadFile","Project",new{ProjectId= ViewBag.ProjectId })',
            onUploaded: function(e) {
                sucNotify('上传成功');
                initAttachment();
                hideLoading();
            }
        });
        $('#project-map-upload').dxFileUploader(config);

        initAttachment();
    });

    function initAttachment() {

        var config = dxConfig.gallery({
            dataSource: DevExpress.data.AspNet.createStore({
                key: 'id',
                loadUrl: '@Url.Action("GetProjectAttachments", "Project", new { ProjectId = ViewBag.ProjectId })'
            }),
            height: 800,
            width: '100%',
            loop: true,
            slideshowDelay: 20000,
            //elementAttr: {
            //    id: 'elementId',
            //    class: 'class-name'
            //},
            itemTemplate: function (item, index, itemElement) {
                $('<img id="' + item.Order + '">').attr('src', item.VirtualPath).attr('filePath', item.FilePath).addClass('dx-gallery-item-image')
                    //.attr('width', '98%')
                    //.attr('width', 'auto').attr('height', 'auto')
                    //.attr('max-width', '100%').attr('max-height', '100%')
                    .dxContextMenu({
                        dataSource: [{ text: '删除' }],
                        width: 200,
                        target: '#' + item.Order,//item.Order,
                        filePath: item.FilePath,
                        onItemClick: function (f) {
                            //f.component._options.filePath// f.element.attr('filePath')
                            syncGet('/api/parakeet/Project/RemoveAttachment?path=' + f.component._options.filePath,
                                function (r) { },
                                function (res, d) {
                                    initAttachment();
                                });
                        }
                    })
                    .appendTo(itemElement);
                $('<div>').addClass('item-file-name').text(item.FileName).appendTo(itemElement);
                return itemElement;
            }
            //itemTemplate: $("#item-template"),
            //onItemClick: function (e) {
            //    //showGalleryPopup('查看大图', itemPopupconfig);
            //    debugger;
            //},
            //onItemContextMenu: function (e) {
            //    //删除功能 '/api/parakeet/Project/RemoveAttachment?path='
            //}
        });

        $('#project-map-gallery').dxGallery(config);

    }


</script>