src/Parakeet.Net.Web/ViewComponents/MenuNavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace Parakeet.NetCore.Web.ViewComponents
{
    public class MenuNavigationViewComponent : ViewComponent
    {
        private IConfiguration configuration;
        private IAuthorizationService _authorizationService;
        public MenuNavigationViewComponent(IConfiguration configuration, IAuthorizationService authorizationService)
        {
            this.configuration = configuration;
            _authorizationService = authorizationService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            await Task.Factory.StartNew(() =>
            {
                Console.WriteLine("MenuNavigationViewComponent Initialize");
            });

            ViewData["Authority"] = _authorizationService;//configuration.GetValue<string>("Authority");
            return View();
        }
    }
}

src/Parakeet.Net.Web/ViewComponents/TopNavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace Parakeet.NetCore.Web.ViewComponents
{
    public class TopNavigationViewComponent : ViewComponent
    {
        private IConfiguration _configuration;
        private IAuthorizationService _authorizationService;
        public TopNavigationViewComponent(IConfiguration configuration, IAuthorizationService authorizationService)
        {
            _configuration = configuration;
            _authorizationService = authorizationService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            await Task.Factory.StartNew(() =>
            {
                Console.WriteLine("TopNavigationViewComponent Initialize");
            });

            ViewData["Authority"] = _authorizationService;//configuration.GetValue<string>("Authority");
            return View();
        }
    }
}

src/Parakeet.Net.Web/Views/Shared/_DevExtremeLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>NetCore</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.min.css" />
    <link href="~/css/devextreme/dx.common.css" rel="stylesheet" />
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />
    @RenderSection("styles", required: false)

    <script src="~/js/devextreme/jquery.js"></script>
    <script src="~/js/devextreme/bootstrap.js"></script>

    <script src="~/js/devextreme/cldr.js"></script>
    <script src="~/js/devextreme/cldr/event.js"></script>
    <script src="~/js/devextreme/cldr/supplemental.js"></script>
    <script src="~/js/devextreme/cldr/unresolved.js"></script>

    <script src="~/js/devextreme/globalize.js"></script>
    <script src="~/js/devextreme/globalize/message.js"></script>
    <script src="~/js/devextreme/globalize/number.js"></script>
    <script src="~/js/devextreme/globalize/currency.js"></script>
    <script src="~/js/devextreme/globalize/date.js"></script>

    @* JSZip for client side export *@
    @*<script src="~/js/devextreme/jszip.js"></script>*@

    <script src="~/js/devextreme/dx.all.js"></script>
    <script src="~/js/devextreme/vectormap-data/world.js"></script>
    <script src="~/js/devextreme/localization/dx.messages.zh.js"></script>
    <script src="~/js/devextreme/localization/supplemental.js"></script>
    <script src="~/js/devextreme/localization/zh.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>

</head>

<body>

    <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md">
        <a class="navbar-brand" href="/">NetCore</a>

        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div id="navbar" class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="active nav-item"><a href="#" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="#about" class="nav-link">About</a></li>
                <li class="nav-item"><a href="#contact" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        @RenderBody()
    </main>
    <script>
        Globalize.locale(navigator.languages && navigator.languages[0] ||
            navigator.language ||
            navigator.userLanguage);
    </script>

    <!-- abp -->
    <script src="~/libs/abp/utils/abp-utils.umd.min.js"></script>
    <script src="~/libs/abp/core/abp.js"></script>
    <script src="~/Abp/ApplicationConfigurationScript"></script>
    <script src="~/Abp/ServiceProxyScript"></script>
    @RenderSection("scripts", required: false)
</body>

</html>

src/Parakeet.Net.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="鹦鹉工作室">
    <meta name="author" content="parakeet">

    <title>小鹦鹉工作室</title>
    <link href="~/favicon.gif" rel="shortcut icon" type="image/x-icon" />
    <!--bootstrap v4.3.1-->
    <link href="~/css/devextreme/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/devextreme/dx.common.css" rel="stylesheet" />
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />
    <!-- SLIDER REVOLUTION 4.x CSS SETTINGS -->
    <link rel="stylesheet" type="text/css" href="~/plugins/rs-plugin/css/settings.css" media="screen" asp-append-version="true" />

    <!-- Custom CSS -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet" type="text/css" asp-append-version="true">
    <link href="~/css/ionicons.min.css" rel="stylesheet" asp-append-version="true">
    <link href="~/css/main.css" rel="stylesheet" asp-append-version="true">
    <link href="~/css/style.css" rel="stylesheet" asp-append-version="true">
    <link href="~/css/responsive.css" rel="stylesheet" asp-append-version="true">

    <!-- 网站样式，谷歌字体 CSS COLORS -->
    <link rel="stylesheet" id="color" href="~/css/default.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

    @RenderSection("styles", required: false)
    <!-- JavaScripts modernizr 放在head标签内，兼容Ie -->
    <script src="~/js/modernizr.js"></script>
</head>

<body>
    <div id="wrap" class="container-fluid">

        <!-- header -->
        <header class="header-normal">
            <div class="sticky">
                <div class="container">
                    <!-- Logo -->
                    <div class="logo">
                        <a href="/Home"><img class="img-responsive" width="70" src="~/images/logo-parakeet17.png" alt=""><span>小鹦鹉工作室</span></a>
                    </div>

                    <!-- Navigation -->
                    <nav class="navbar webimenu">
                        <!-- MENU BUTTON RESPONSIVE -->
                        <div class="menu-toggle"> <i class="fa fa-bars"> </i> </div>
                        <!-- NAV -->

                        <ul class="nav ownmenu">
                            <li class="active">
                                <a href="~/home">主页</a>
                                <ul class="dropdown animated-3s fadeIn">
                                    <li> <a href="~/api/parakeet/areaTenant/areaTreeListIndex">区域管理</a> </li>
                                    <li> <a href="~/api/parakeet/areaTenant">区域连接管理</a> </li>
                                </ul>
                            </li>
                            <li>
                                <a href="~/api/parakeet/project/index"> 项目简介 </a>
                                <ul class="dropdown animated-3s fadeIn">
                                    <li> <a href="~/api/parakeet/organization/index">组织架构</a> </li>
                                    <li> <a href="~/api/parakeet/project/index">项目简介</a> </li>
                                </ul>
                            </li>
                            <li>
                                <a href="~/api/parakeet/need/index">用户需求</a>
                                <ul class="dropdown animated-3s fadeIn">
                                    <li> <a href="~/api/parakeet/organization/index">门户网站</a> </li>
                                    <li> <a href="~/api/parakeet/need/create">系统定制</a> </li>
                                    <li> <a href="~/api/parakeet/need/create">公众号</a> </li>
                                    <li> <a href="~/api/parakeet/need/create">小程序</a> </li>
                                </ul>
                            </li>
                            <li>
                                <a href="~/api/parakeet/need/create">联系我们</a>
                                <ul class="dropdown animated-3s fadeIn">
                                    <li> <a href="~/api/parakeet/need/create">联系我们</a> </li>
                                    <li> <a href="~/api/parakeet/need/create">联系我们</a> </li>
                                </ul>
                            </li>
                            @Html.Partial("_LoginPartial")
                            <li><img class="parakeet" width="60" src="~/images/parakeet.png" alt="" /></li>
                        </ul>

                    </nav>
                </div>
            </div>
        </header>

        <!-- Content -->
        <div id="content">
            <div class="base-content">
                @RenderBody()
            </div>
        </div>

    </div>

    <!-- JavaScripts jquery bootstrap(v4.3.1) -->
    <!-- jquery vv3.4.1 -->
    <script src="~/js/devextreme/jquery.min.js"></script>
    <script src="~/js/devextreme/bootstrap.min.js"></script>

    <!-- 皮肤 -->
    <script src="~/js/own-menu.js"></script>
    <script src="~/js/jquery.lighter.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/color-switcher.js"></script>

    <!-- DevExtreme cldr & globalize jszip all mvc data SCRIPTS  -->
    <script src="~/js/devextreme/cldr.js"></script>
    <script src="~/js/devextreme/cldr/event.js"></script>
    <script src="~/js/devextreme/cldr/supplemental.js"></script>
    <script src="~/js/devextreme/cldr/unresolved.js"></script>
    <script src="~/js/devextreme/globalize.js"></script>
    <script src="~/js/devextreme/globalize/message.js"></script>
    <script src="~/js/devextreme/globalize/number.js"></script>
    <script src="~/js/devextreme/globalize/currency.js"></script>
    <script src="~/js/devextreme/globalize/date.js"></script>
    <script src="~/js/devextreme/jszip.js"></script>
    <script src="~/js/devextreme/dx.all.js"></script>
    <script src="~/js/devextreme/vectormap-data/world.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js" asp-append-version="true"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js" asp-append-version="true"></script>

    <!-- DevExtreme Localization SCRIPTS  本地化-->
    <script src="~/js/devextreme/localization/dx.messages.zh.js" asp-append-version="true"></script>
    <script src="~/js/devextreme/localization/supplemental.js" asp-append-version="true"></script>
    <script src="~/js/devextreme/localization/zh.js" asp-append-version="true"></script>

    <!-- DevExtreme Extension SCRIPTS  devextreme扩展-->
    <script src="~/plugins/devextreme/dx.extension.js" asp-append-version="true"></script>
    <script src="~/plugins/devextreme/dx.page.extension.js" asp-append-version="true"></script>
    <script src="~/plugins/devextreme/common.js" asp-append-version="true"></script>
    
    <!-- dxDragFiles SCRIPTS  -->
    <script src="~/plugins/drags/dxDragFiles.js" asp-append-version="true"></script>

    <!-- jquery-validation SCRIPTS 验证-->
    <partial name="_ValidationScriptsPartial" />

    <!-- site SCRIPTS  -->
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("scripts", required: false)

</body>

</html>

src/Parakeet.Net.Web/Views/Shared/_LayoutDefault.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="小鹦鹉工作室" />
    <meta name="description" content="致力于复杂业务系统定制！咨询服务热线:17772433927" />
    <meta name="author" content="小鹦鹉工作室" />
    <link rel="icon" type="image/png" sizes="16x16" href="~/favicon.png" />
    <title>NetCore</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />

    <!-- Bootstrap Core CSS  v4.3.1-->
    @*<link href="~/css/devextreme/bootstrap.css" rel="stylesheet" />*@
    <!-- Bootstrap Core CSS v3.3.7-->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Menu CSS -->
    <link href="~/lib/sidebar-nav/dist/sidebar-nav.min.css" rel="stylesheet">
    <!-- color CSS -->
    <link href="~/css/colors/default.css" id="theme" rel="stylesheet">
    <!-- devextreme CSS -->
    <link href="~/css/devextreme/dx.common.css" rel="stylesheet" />
    <link href="~/css/devextreme/dx.light.css" rel="stylesheet" />
    <!-- 谷歌字体 CSS -->
    <link rel="stylesheet" href="~/css/site.min.css" />
    <!-- animation CSS -->
    <link href="~/css/animateDefault.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/css/styleDefault.css" rel="stylesheet">
    @await RenderSectionAsync("styles", false)

    <!-- jQuery 2.1.4-->
    <!--<script src="~/lib/jquery/dist/jquery.min.js"></script>-->
    <!-- jQuery 3.4.1-->
    <script src="~/js/devextreme/jquery.js"></script>

    <!-- Bootstrap Core JavaScript v4.3.1-->
    <!--<script src="~/js/devextreme/bootstrap.js"></script>-->
    <!-- Bootstrap Core JavaScript v3.3.7-->
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- JavaScripts modernizr 放在head标签内，兼容Ie -->
    <script src="~/js/modernizr.js"></script>
</head>

<body class="fix-header">

    <!-- Preloader -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <!-- End Preloader -->
    <!-- Wrapper -->
    <div id="wrapper">
        <!-- Topbar header - style you can find in pages.scss -->
        <nav class="navbar navbar-default navbar-static-top m-b-0">
            <div class="navbar-header">
                <div class="top-left-part">
                    <!-- Logo -->
                    <a class="logo" href="/">
                        <!-- Logo icon image, you can use font-icon also -->
                        <b>
                            <!--This is dark logo icon-->
                            <img src="~/images/admin-logo.png" alt="home" class="dark-logo" />
                            <!--This is light logo icon-->
                            <img src="~/images/admin-logo-dark.png" alt="home" class="light-logo" />
                        </b>
                        <!-- Logo text image you can use text also -->
                        <span class="hidden-xs">
                            <!--This is dark logo text-->
                            <img src="~/images/admin-text.png" alt="home" class="dark-logo" />
                            <!--This is light logo text-->
                            <img src="~/images/admin-text-dark.png" alt="home" class="light-logo" />
                        </span>
                    </a>
                </div>
                <!-- /Logo -->
                <ul class="nav navbar-top-links navbar-left">
                    <li><a class="open-close waves-effect waves-light"><i class="ti-menu"></i></a></li>
                </ul>
                @await Component.InvokeAsync("TopNavigation")
            </div>
            <!-- /.navbar-header -->
            <!-- /.navbar-top-links -->
            <!-- /.navbar-static-side -->
        </nav>
        <!-- End Top Navigation -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <div class="navbar-default sidebar" role="navigation">
            @await Component.InvokeAsync("MenuNavigation")
        </div>
        <!-- End Left Sidebar -->
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <!--Main Region-->
                @RenderBody()
                <!--End Main Region-->
                <!-- Right Sidebar -->
                <div class="right-sidebar">
                    <div class="slimscrollright">
                        <div class="rpanel-title"> 皮肤面板 <span><i class="ti-close right-side-toggle"></i></span> </div>
                        <div class="r-panel-body">
                            <ul id="themecolors" class="m-t-20">
                                <li><b>浅色侧边栏</b></li>
                                <li><a href="javascript:void(0)" data-theme="default" class="default-theme">1</a></li>
                                <li><a href="javascript:void(0)" data-theme="green" class="green-theme">2</a></li>
                                <li><a href="javascript:void(0)" data-theme="gray" class="yellow-theme">3</a></li>
                                <li><a href="javascript:void(0)" data-theme="blue" class="blue-theme">4</a></li>
                                <li><a href="javascript:void(0)" data-theme="purple" class="purple-theme">5</a></li>
                                <li><a href="javascript:void(0)" data-theme="megna" class="megna-theme">6</a></li>
                                <li><b>深色侧边栏</b></li>
                                <br />
                                <li><a href="javascript:void(0)" data-theme="default-dark" class="default-dark-theme">7</a></li>
                                <li><a href="javascript:void(0)" data-theme="green-dark" class="green-dark-theme">8</a></li>
                                <li><a href="javascript:void(0)" data-theme="gray-dark" class="yellow-dark-theme">9</a></li>
                                <li><a href="javascript:void(0)" data-theme="blue-dark" class="blue-dark-theme">10</a></li>
                                <li><a href="javascript:void(0)" data-theme="purple-dark" class="purple-dark-theme">11</a></li>
                                <li><a href="javascript:void(0)" data-theme="megna-dark" class="megna-dark-theme working">12</a></li>
                            </ul>
                            <ul class="m-t-20 all-demos">
                                <li><b>期待更多模板...</b></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <!-- End Right Sidebar -->
            </div>
            <!-- /.container-fluid -->
            <footer class="footer text-center"> @DateTime.Now.Year &copy; 小鹦鹉工作室 </footer>
        </div>
        <!-- End Page Content -->
    </div>
    <!-- /#wrapper -->
    <!-- Menu Plugin JavaScript -->
    <script src="~/lib/sidebar-nav/dist/sidebar-nav.min.js"></script>
    <!--Style Switcher -->
    <script src="~/lib/styleswitcher/jQuery.style.switcher.js"></script>
    <!--slimscroll JavaScript -->
    <script src="~/js/jquery.slimscroll.js"></script>
    <!--Wave Effects -->
    <script src="~/js/waves.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="~/js/custom.js"></script>

    <!-- DevExtreme cldr & globalize jszip all mvc data SCRIPTS  -->
    <script src="~/js/devextreme/cldr.js"></script>
    <script src="~/js/devextreme/cldr/event.js"></script>
    <script src="~/js/devextreme/cldr/supplemental.js"></script>
    <script src="~/js/devextreme/cldr/unresolved.js"></script>
    <script src="~/js/devextreme/globalize.js"></script>
    <script src="~/js/devextreme/globalize/message.js"></script>
    <script src="~/js/devextreme/globalize/number.js"></script>
    <script src="~/js/devextreme/globalize/currency.js"></script>
    <script src="~/js/devextreme/globalize/date.js"></script>
    <script src="~/js/devextreme/jszip.js"></script>
    <script src="~/js/devextreme/dx.all.js"></script>
    <script src="~/js/devextreme/vectormap-data/world.js"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.mvc.js" asp-append-version="true"></script>
    <script src="~/js/devextreme/aspnet/dx.aspnet.data.js" asp-append-version="true"></script>

    <!-- DevExtreme Localization SCRIPTS  本地化-->
    <script src="~/js/devextreme/localization/dx.messages.zh.js" asp-append-version="true"></script>
    <script src="~/js/devextreme/localization/supplemental.js" asp-append-version="true"></script>
    <script src="~/js/devextreme/localization/zh.js" asp-append-version="true"></script>

    <!-- DevExtreme Extension SCRIPTS  devextreme扩展-->
    <script src="~/plugins/devextreme/dx.extension.js" asp-append-version="true"></script>
    <script src="~/plugins/devextreme/dx.page.extension.js" asp-append-version="true"></script>
    <script src="~/plugins/devextreme/common.js" asp-append-version="true"></script>

    <!-- dxDragFiles SCRIPTS  -->
    <script src="~/plugins/drags/dxDragFiles.js" asp-append-version="true"></script>

    <!-- jquery-validation SCRIPTS 验证-->
    <partial name="_ValidationScriptsPartial" />

    <!-- site SCRIPTS  -->
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- abp -->
    <script src="~/libs/abp/utils/abp-utils.umd.min.js"></script>
    <script src="~/libs/abp/core/abp.js"></script>
    <script src="~/Abp/ApplicationConfigurationScript"></script>
    <script src="~/Abp/ServiceProxyScript"></script>
    @await RenderSectionAsync("scripts", false)
</body>
</html>

src/Parakeet.Net.Web/Views/Shared/_bundleScript.cshtml
@*<abp-script-bundle>
            <abp-script src="/js/devextreme/cldr.min.js" />
            <abp-script src="/js/devextreme/cldr/event.min.js" />
            <abp-script src="/js/devextreme/cldr/supplemental.min.js" />
            <abp-script src="/js/devextreme/cldr/unresolved.min.js" />
            <abp-script src="/js/devextreme/globalize.min.js" />
            <abp-script src="/js/devextreme/globalize/message.min.js" />
            <abp-script src="/js/devextreme/globalize/number.min.js" />
            <abp-script src="/js/devextreme/globalize/currency.min.js" />
            <abp-script src="/js/devextreme/globalize/date.min.js" />
            <abp-script src="/js/devextreme/jszip.min.js" />
            <abp-script src="/js/devextreme/dx.all.js" />
            <abp-script src="/js/devextreme/vectormap-data/world.js" />
            <abp-script src="/js/devextreme/aspnet/dx.aspnet.mvc.js" />
            <abp-script src="/js/devextreme/aspnet/dx.aspnet.data.js" />
            <abp-script src="/js/devextreme/localization/dx.messages.zh.js" />
            <abp-script src="/js/devextreme/localization/supplemental.js" />
            <abp-script src="/js/devextreme/localization/zh.js" />
            <abp-script src="/plugins/devextreme/dx.extension.js" />
            <abp-script src="/plugins/devextreme/dx.page.extension.js" />
            <abp-script src="/plugins/devextreme/common.js" />
            <abp-script src="/plugins/jquery-validation/dist/localization/messages_zh.js" />
            <abp-script src="/plugins/drags/dxDragFiles.js" />
            <abp-script src="/js/site.js" />
        </abp-script-bundle>

    <script src="/js/devextreme/cldr.min.js"></script>
    <script src="/js/devextreme/cldr/event.min.js"></script>
    <script src="/js/devextreme/cldr/supplemental.min.js"></script>
    <script src="/js/devextreme/cldr/unresolved.min.js"></script>
    <script src="/js/devextreme/globalize.min.js"></script>
    <script src="/js/devextreme/globalize/message.min.js"></script>
    <script src="/js/devextreme/globalize/number.min.js"></script>
    <script src="/js/devextreme/globalize/currency.min.js"></script>
    <script src="/js/devextreme/globalize/date.min.js"></script>
    <script src="/js/devextreme/jszip.min.js"></script>
    <script src="/js/devextreme/dx.all.js"></script>
    <script src="/js/devextreme/vectormap-data/world.js"></script>
    <script src="/js/devextreme/aspnet/dx.aspnet.mvc.js"></script>
    <script src="/js/devextreme/aspnet/dx.aspnet.data.js"></script>
    <script src="/js/devextreme/localization/dx.messages.zh.js"></script>
    <script src="/js/devextreme/localization/supplemental.js"></script>
    <script src="/js/devextreme/localization/zh.js"></script>
    <script src="/plugins/devextreme/dx.extension.js"></script>
    <script src="/plugins/devextreme/dx.page.extension.js"></script>
    <script src="/plugins/devextreme/common.js"></script>
    <script src="/plugins/jquery-validation/dist/localization/messages_zh.js"></script>
    <script src="/plugins/drags/dxDragFiles.js"></script>
    <script src="/js/site.js"></script>*@

src/Parakeet.Net.Web/Views/Shared/_bundleStyle.cshtml
@*<abp-style-bundle>
            <abp-style src="/plugins/rs-plugin/css/settings.css" />
            <abp-style src="/css/main.css" />
            <abp-style src="/css/style.css" />
            <!--以上三个都是主页需要的，可以不引用，不能放压缩main里面有语法错误->

            <abp-style src="/css/font-awesome.min.css" />
            <abp-style src="/css/ionicons.min.css" />
            <abp-style src="/css/responsive.css" />
            <abp-style src="/css/default.css" />
            <abp-style src="/css/site.min.css" />
        </abp-style-bundle>
    <link rel="stylesheet" href="/plugins/rs-plugin/css/settings.css" />
    <link rel="stylesheet" href="/css/font-awesome.min.css" />
    <link rel="stylesheet" href="/css/ionicons.min.css" />
    <link rel="stylesheet" href="/css/main.css" />
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/responsive.css" />
    <link rel="stylesheet" href="/css/default.css" />
    <link rel="stylesheet" href="/css/site.min.css" />*@