src/Parakeet.Net.Web/Controllers/NeedController.cs
using Common.Dtos;
using Common.Entities;
using Common.Extensions;
using Common.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using Volo.Abp.Settings;

namespace Parakeet.Net.Controllers
{
    /// <summary>
    /// 需求
    /// </summary>
    [ApiController]
    [ApiExplorerSettings(GroupName = "V1")]
    [Route("/api/parakeet/need/[action]")]
    //[Authorize]//默认策略 [Authorize(Scheme="CustomPolicy")]//自定义策略   [Authorize(Roles="admin,Custom")] 角色鉴权
    public class NeedController : BaseNetEntityController<Need>
    {
        private readonly IWebHostEnvironment _environment;
        private readonly INeedAppService _needAppService;
        private readonly INeedAttachmentAppService _needAttachmentAppService;
        //private readonly IPersonalCacheAppService _personalCacheAppService;
        //private readonly ISettingProvider _settingProvider;
        //private readonly IEmailSender _emailSender;
        //private readonly IHttpClientFactory _clientFactory;
        public NeedController(INeedAppService baseService,
            INeedAttachmentAppService needAttachmentService,
            IWebHostEnvironment environment,
            //IPersonalCacheAppService personalCacheAppService,
            //IHttpClientFactory clientFactory,
            //IEmailSender emailSender,
            ISettingProvider settingProvider) : base(baseService)
        {
            _needAppService = baseService;
            _needAttachmentAppService = needAttachmentService;
            _environment = environment;
            //_personalCacheAppService = personalCacheAppService;
            //_settingProvider = settingProvider;
            //_clientFactory = clientFactory;
            //_emailSender = emailSender;
        }


        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpGet, ResponseCache(Duration = 6000)]//缓存6000s
        public IActionResult Create()
        {
            return View();
        }

        #region  POST: Need/Create

        [HttpPost]
        public async Task<IActionResult> Create([FromForm] NeedCreateDto input)
        {
            return DJson(await _needAppService.Create(input));
        }
        #endregion


        /// <summary>
        /// UploadFile Request.Form.Files接收文件 Request.Form["uploadGuid"]传递uploadGuid
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> UploadFile(InputIdDto input)
        {
            //直接使用IFormFile uploadFile参数文件过大使用参数获取会出现序列化错误
            await _needAppService.UploadFiles(input);
            return SJson();
        }

        /// <summary>
        /// 提供给用户下载
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Download(InputIdDto input)
        {
            var attachment = await _needAttachmentAppService.GetByPrimaryKey(input);
            var path = attachment?.Attachment?.Path ?? Path.Combine(_environment.WebRootPath, attachment?.Attachment?.VirtualPath);
            var memoryStream = new MemoryStream();
            await using (var stream = new FileStream(path, FileMode.Open))
            {
                await stream.CopyToAsync(memoryStream);
            }
            memoryStream.Seek(0, SeekOrigin.Begin);
            //文件名必须编码，否则会有特殊字符(如中文)无法在此下载。
            string encodeFilename = HttpUtility.UrlEncode(Path.GetFileName(path), Encoding.GetEncoding("UTF-8"));
            base.Response.Headers.Append("Content-Disposition", "attachment; filename=" + encodeFilename);
            return new FileStreamResult(memoryStream, "application/octet-stream");
        }

        /// <summary>
        /// 下载物理文件(给img标签 src属性)
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> DownloadFile(InputIdDto input)
        {
            var attachment = await _needAttachmentAppService.GetByPrimaryKey(input);
            if (attachment is null)
            {
                return null;
            }
            var path = attachment?.Attachment?.Path ?? Path.Combine(_environment.WebRootPath, attachment?.Attachment?.VirtualPath);
            return PhysicalFile(path, "image/jpg", Path.GetFileName(path));//PhysicalFile 直接返回物理文件,给href
        }

        /// <summary>
        /// 提供给用户删除文件
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> RemoveAttachment(InputIdDto input)
        {
            var attachment = await _needAttachmentAppService.GetByPrimaryKey(input);
            if (attachment?.Attachment is null)
            {
                return null;
            }
            var path = attachment.Attachment.Path ?? $@"{_environment.WebRootPath}{attachment.Attachment.VirtualPath}";
            FileExtension.ClearFile(path);
            FileExtension.CheckClearParentDir(path);
            await _needAttachmentAppService.GetBaseRepository().DeleteAsync(input.Id);
            return SJson();
        }



        /// <summary>
        /// 打开邮件时自动进入 <img style='display:none;' src='" + domail + "User/IsReader?username=zhangsan' />
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task ReadEmail(InputIdDto input)
        {
            //如果能进入，代表别人已经看了
            //统计input.Id 已经看了多少次
            var need = await _needAppService.GetByPrimaryKey(input);
            need.IsRead = true;
            need.ReadTime = DateTime.Now;
            Log.Logger.Information($"{need.Name}{need.ReadTime}读取邮件");
        }
    }
}

src/Parakeet.Net.Web/Views/Need/Add.cshtml
@model Common.Dtos.NeedDto;

@{
    var formId = Guid.NewGuid().ToString();
}
@section Styles {

    <style>
        .block {
            display: block;
        }

        form label.error {
            display: none;
        }

        /*批量上传文件区域样式*/
        .upload-container {
            /*width: 600px;*/
            height: 400px;
            border: 1px solid lightgray;
            display: flex;
            justify-content: center;
            align-items: center;
            font-size: 26px;
        }

        .drag-container {
            float: left;
            margin-right: 80px;
            padding: 0;
            width: 100%;
        }

        .thumb {
            height: 100px;
            max-width: 100px;
            border: 1px solid #000;
            margin: 10px 5px 0 0;
        }

        /*tilevView*/
        .dx-tile-content {
            height: 100%;
        }

            .dx-tile-content .image {
                height: 100%;
                width: 100%;
                /*background-position: center;
            background-size: cover;*/
                display: block;
            }

        /*隐藏useBotton的上传按钮*/
        #fileUploader .dx-fileuploader-upload-button {
            display: none;
        }
    </style>

}

<div class="form">
    <form action="@Url.Action("Create", "Need")" method="post" class="form-horizontal" role="form" id="needForm" data-guid="@formId" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div id="form-container"></div>
            </div>
        </div>
    </form>
</div>



<div class="container">
    <h2>内联表单</h2>
    <form class="form-inline">
        <label for="email">Email:</label>
        <input type="email" class="form-control" id="email" placeholder="Enter email">
        <label for="pwd">Password:</label>
        <input type="password" class="form-control" id="pwd" placeholder="Enter password">
        <div class="form-check">
            <label class="form-check-label">
                <input class="form-check-input" type="checkbox"> Remember me
            </label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <h2>表单控件: input</h2>
    <p>以下实例使用两个 input 元素，一个是 text，一个是 password ：</p>
    <form>
        <div class="form-group">
            <label for="usr">用户名:</label>
            <input type="text" class="form-control" id="usr">
        </div>
        <div class="form-group">
            <label for="pwd">密码:</label>
            <input type="password" class="form-control" id="pwd">
        </div>
    </form>

    <h2>表单控件: textarea</h2>
    <p>以下实例演示了 textarea 的样式。</p>
    <form>
        <div class="form-group">
            <label for="comment">评论:</label>
            <textarea class="form-control" rows="5" id="comment"></textarea>
        </div>
    </form>

    <h2>表单控件: checkbox</h2>
    <p>以下实例包含了三个选项。最后一个是禁用的：</p>
    <form>
        <div class="form-check">
            <label class="form-check-label">
                <input type="checkbox" class="form-check-input" value="">Option 1
            </label>
        </div>
        <div class="form-check">
            <label class="form-check-label">
                <input type="checkbox" class="form-check-input" value="">Option 2
            </label>
        </div>
        <div class="form-check disabled">
            <label class="form-check-label">
                <input type="checkbox" class="form-check-input" value="" disabled>Option 3
            </label>
        </div>
    </form>
    <h2>表单控件: checkbox</h2>
    <p>以下实例包含了三个选项。最后一个是禁用的，使用 .form-check-inline 类可以让选项显示在同一行上：</p>
    <form>
        <div class="form-check form-check-inline">
            <label class="form-check-label">
                <input type="checkbox" class="form-check-input" value="">Option 1
            </label>
        </div>
        <div class="form-check form-check-inline">
            <label class="form-check-label">
                <input type="checkbox" class="form-check-input" value="">Option 2
            </label>
        </div>
        <div class="form-check form-check-inline disabled">
            <label class="form-check-label">
                <input type="checkbox" class="form-check-input" value="" disabled>Option 3
            </label>
        </div>
    </form>
</div>